name: Test Workflow

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f2005289@ds.study.iitm.ac.in
        run: echo "Hello, world!"
